app:
  serverPort: :9000
  logLevel: debug

mysql:
  host: 127.0.0.1
  port: 3306
  database: eve
  username: root
  password: OysEY7eEdupLBWlct//HzuaIcG+aPW63BGCMCUVU1Ajms6i3Eu86y59gr4Qabozie46WYeCl1c0aMTd/T84AElJGGGatNIB6A+/2MhsTl6hFFr9qlyJFH/+4EYkMW8mXICVkq8asncfTFJj5sB0FbEkCC3g6uTMeq/Zv2uRb588=
  charset: utf8
  loc: Asia/Shanghai
  maxIdleConn: 10
  maxOpenConn: 100
  connMaxLifetime: 600
  autoMigrate: false

redis:
  address: 127.0.0.1:6379
  password: YRzHd/5O2pnm/Ns3wSq1h1pZxU+WDKWpwn0uUHEZ4BOsAffXThtJH/9ag4Ot2tyUWOv2VtUBO/ErD1rcJ0gEeDMrOq8qk7zmd8ogOW0AL7p7L+VxJrLSAvIpwIcjV+2DohRKOeXcBv582h/2NloNXloKhMWUEIFVYMJnsbW2r/E=
  database: 0
  refresh: false
  expireTime:
    history: -1
    order: -1
    model: -1

data: 
  local:  
    path: C://Dev//projects//evelp//scripts//
    refresh: false
  remote: 
    address: https://esi.evetech.net/latest
    datasource: tranquility
    refresh: false

crypto:
  keyPath: C://Dev//projects//certs//private_key.pem